### ISSUE TITLE
associate data from one topology aspect to another

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/xugrid#127] opened 2023-07-28 09:58 UTC
It would be a nice addition to "interpolate" e.g. edge variables to faces, or nodes to edges, or any other shift in topology aspect. Currently, there is a [node/edge-to-face interpolation function in dfm_tools](https://github.com/Deltares/dfm_tools/blob/7b5d896c6b3eb1059be4e9e148ef0bfc0c258756/dfm_tools/xugrid_helpers.py#L444-L514), but this is a bit too specific and it would be great to land this in xugrid instead.

It would be nice if the user can do things like:
```
uda = uds[edge_var]
uda.to_faces()

uda = uds[node_var]
uda.to_edges()
```

**Comment by Huite** [comment] 2024-07-22 08:46
Duplicate of: https://github.com/Deltares/xugrid/issues/173

(This was first, but I wrote more in the other one...)

**Closed by Huite** 2024-07-22 08:46 UTC
