### ISSUE TITLE
After xu.concat(): selection and depth conversion issues

### ISSUE THREAD

**Issue by Sonia-Heye** [Deltares/xugrid#80] opened 2023-04-25 09:45 UTC
Hey, 
I've found an issue when using concatenated datasets, following xu.concat(). 
Firstly, my ds.ugrid.sel() function gives me an index error with the concatenated data. 
Secondly, my depth conversion from sigma to meters (dfmt.get_Dataset_atdepths()) only works before the data is concatenated - and also does not work on the point-selected output from the first issue. 
An example: P:\\11208479-sequestration-seaweed\\Oosterschelde_DFM_hydro_waq\\dflowfm3d-oosterschelde-wq\\scripts\\issue_minimal_working_example.ipynb

Or:

```python
import os
from pathlib import Path
import geopandas
import pandas as pd
import xugrid as xu
import dfm_tools as dfmt
from shapely.geometry import Point

## Reading output from 2 years, for 3 partitions

basedir = r"p:\archivedprojects\11206044-002ospareutrophication\final_results_Snellius_latestversion_20220210"
f1 = [os.path.join(basedir, r'A16b_Numtopsiguniform1_2015_pH\DFM_OUTPUT_DCSM-FM_0_5nm_waq',f'DCSM-FM_0_5nm_waq_{i:04d}_map.nc') for i in [146,147,148]]
f2 = [os.path.join(basedir, r'A16b_Numtopsiguniform1_2016_pH\DFM_OUTPUT_DCSM-FM_0_5nm_waq',f'DCSM-FM_0_5nm_waq_{i:04d}_map.nc') for i in [146,147,148]]

waq_xr1 = dfmt.open_partitioned_dataset(f1)       # opens every .map file in this folder
waq_xr2 = dfmt.open_partitioned_dataset(f2)

waq_xr1 = dfmt.rename_waqvars(waq_xr1)             # renames the water quality variables
waq_xr2 = dfmt.rename_waqvars(waq_xr2)

waq_xr = xu.concat([waq_xr1, waq_xr2], dim='time') # concatenate the two years


list_plifiles = [Path(r'p:\11208479-sequestration-seaweed\Oosterschelde_DFM_hydro_waq\dflowfm3d-oosterschelde-wq\boundary_conditions\zee-zuid.pli')]


## Loop over each boundary

for i,file in list(enumerate(list_plifiles)):
    print(str(file).split('\\')[-1].split('.')[0])
    
    # Read points within this offshore boundary:
    pli_file = pd.read_csv(list_plifiles[i], skiprows=1, sep=' ')   # read pli file
    pli_file = pli_file.dropna(axis=1)                              # drop empty columns
    # Convert dutch crs to decimal degrees (for DCSM)
    points = [] 
    for i in range(0,len(pli_file)):
        points.append(Point(pli_file[pli_file.columns[0]].to_list()[i], pli_file[pli_file.columns[1]].to_list()[i]))
    d = {'location': pli_file[pli_file.columns[2]].to_list(), 'geometry': points}
    gdf = geopandas.GeoDataFrame(d, crs='epsg:28992')   # set Dutch crs
    gdf = gdf.to_crs(4326)                              # convert to decimal degrees


point = 0


## Issue when using .sel from concatenated ds: 
waq_xr.ugrid.sel(x=gdf.geometry[point].x, y=gdf.geometry[point].y)

## Note: no issue with pre-concatenated data
ds_point = waq_xr1.ugrid.sel(x=gdf.geometry[point].x, y=gdf.geometry[point].y)

## Issue with depth conversion from sigma to meters:
dfmt.get_Dataset_atdepths(data_xr=ds_point, depths = waq_xr.mesh2d_layer_z[0,:].values)  ## using point selected from above

dfmt.get_Dataset_atdepths(data_xr=waq_xr, depths = waq_xr.mesh2d_layer_z[0,:].values)  # Also issue when using concat data

## But no issue when using 1 year (pre-concat and pre-point-selection):
dfmt.get_Dataset_atdepths(data_xr=waq_xr1, depths=waq_xr.mesh2d_layer_z[0,:].values.tolist(), reference='waterlevel')
```

**Comment by veenstrajelmer** [comment] 2024-09-05 11:14
I ran the code in the issue description again. Most of the lines work without errors. However, there is still one issue left. When interpolating the merged dataset (`waq_xr`) to depths, it raises `"ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"`. This is because the `mesh2d_interface_z` variable (and possibly others), has an additional `time` dimension. Reproducible code:
```python
import os
import xugrid as xu
import dfm_tools as dfmt

## Reading output from 2 years, for 3 partitions
basedir = r"p:\archivedprojects\11206044-002ospareutrophication\final_results_Snellius_latestversion_20220210"
f1 = [os.path.join(basedir, r'A16b_Numtopsiguniform1_2015_pH\DFM_OUTPUT_DCSM-FM_0_5nm_waq',f'DCSM-FM_0_5nm_waq_{i:04d}_map.nc') for i in [146,147,148]]
f2 = [os.path.join(basedir, r'A16b_Numtopsiguniform1_2016_pH\DFM_OUTPUT_DCSM-FM_0_5nm_waq',f'DCSM-FM_0_5nm_waq_{i:04d}_map.nc') for i in [146,147,148]]

waq_xr1 = dfmt.open_partitioned_dataset(f1)       # opens every .map file in this folder
waq_xr2 = dfmt.open_partitioned_dataset(f2)

waq_xr1 = dfmt.rename_waqvars(waq_xr1)             # renames the water quality variables
waq_xr2 = dfmt.rename_waqvars(waq_xr2)

waq_xr = xu.concat([waq_xr1, waq_xr2], dim='time') # concatenate the two years

# this raises "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"
# dfmt.get_Dataset_atdepths(data_xr=waq_xr, depths = waq_xr.mesh2d_layer_z[0,:].values)

print(waq_xr2['mesh2d_interface_z'].dims) # ('mesh2d_nInterfaces',)
print(waq_xr['mesh2d_interface_z'].dims) # ('time', 'mesh2d_nInterfaces')
```

Prints:
```
('mesh2d_nInterfaces',)
('time', 'mesh2d_nInterfaces')
```

Is this a bug or should one use a different approach to concatenate the datasets?

**Comment by Huite** [comment] 2024-09-05 11:18
I think it needs a different option for one of the keywords:

https://docs.xarray.dev/en/stable/generated/[xarray.concat](https://docs.xarray.dev/en/stable/generated/xarray.concat.html).html

**Comment by veenstrajelmer** [comment] 2024-09-05 11:34
Thanks, you are right, I missed `data_vars='minimal'`. This avoids the time dimension being broadcasted on variables without it.

This code should do all the intented things and gives no errors:
```python
import os
import geopandas
import pandas as pd
import xugrid as xu
import dfm_tools as dfmt
from shapely.geometry import Point

## Reading output from 2 years, for 3 partitions
basedir = r"p:\archivedprojects\11206044-002ospareutrophication\final_results_Snellius_latestversion_20220210"
f1 = [os.path.join(basedir, r'A16b_Numtopsiguniform1_2015_pH\DFM_OUTPUT_DCSM-FM_0_5nm_waq',f'DCSM-FM_0_5nm_waq_{i:04d}_map.nc') for i in [146,147,148]]
f2 = [os.path.join(basedir, r'A16b_Numtopsiguniform1_2016_pH\DFM_OUTPUT_DCSM-FM_0_5nm_waq',f'DCSM-FM_0_5nm_waq_{i:04d}_map.nc') for i in [146,147,148]]

# opens every .map file in this folder
waq_xr1 = dfmt.open_partitioned_dataset(f1)
waq_xr2 = dfmt.open_partitioned_dataset(f2)

# rename the water quality variables
waq_xr1 = dfmt.rename_waqvars(waq_xr1)
waq_xr2 = dfmt.rename_waqvars(waq_xr2)

# concatenate the two years
waq_xr = xu.concat([waq_xr1, waq_xr2], 
                   dim='time', # dimension along which to concatenate
                   data_vars='minimal' # to avoid expanding of non-time variables with time dimension
                   )

file_pli = r'p:\11208479-sequestration-seaweed\Oosterschelde_DFM_hydro_waq\dflowfm3d-oosterschelde-wq\boundary_conditions\zee-zuid.pli'

# Read points within this offshore boundary:
pli_file = pd.read_csv(file_pli, skiprows=1, sep=' ')  # read pli file
pli_file = pli_file.dropna(axis=1)  # drop empty columns
# Convert dutch crs to decimal degrees (for DCSM)
points = [] 
for i in range(0,len(pli_file)):
    points.append(Point(pli_file[pli_file.columns[0]].to_list()[i], pli_file[pli_file.columns[1]].to_list()[i]))
d = {'location': pli_file[pli_file.columns[2]].to_list(), 'geometry': points}
gdf = geopandas.GeoDataFrame(d, crs='epsg:28992')  # set Dutch crs
gdf = gdf.to_crs(4326)  # convert to decimal degrees

point = 0

ds_point = waq_xr.ugrid.sel(x=gdf.geometry[point].x, y=gdf.geometry[point].y)

ds_point_atdepths = dfmt.get_Dataset_atdepths(data_xr=ds_point, depths=waq_xr.mesh2d_layer_z[0].values)

waq_xr_atdepths = dfmt.get_Dataset_atdepths(data_xr=waq_xr, depths=waq_xr.mesh2d_layer_z[0].values)
```

**Closed** 2024-09-05 11:35 UTC
